src/objects/Student__c.object
<CustomObject>
    <description>This object stores information about CRJ students.</description>
    <fields>
        <fullName>Graduate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the student has graduated.</description>
        <label>Graduate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsWorking__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsWorking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Split_Time_Sponsor_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Split Time Sponsor Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students (Split Time Sponsor Contact)</relationshipLabel>
        <relationshipName>Students1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Time_Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Split Time Sponsor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students (Split Time Sponsor)</relationshipLabel>
        <relationshipName>Students1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_time__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if student works at more than one sponsor.</inlineHelpText>
        <label>Split time</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sponsor_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students (Sponsor Contact)</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <description>Student&apos;s email address</description>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Withdrawn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Withdrawn from CRJ?</description>
        <inlineHelpText>Check if student has withdrawn from CRJ.</inlineHelpText>
        <label>Withdrawn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Day__c</fullName>
        <description>This is the day the student works each week.</description>
        <inlineHelpText>What day of the week does the student work?</inlineHelpText>
        <label>Work Day</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <description>Time Card used to track a student&apos;s daily hours and performance at their sponsor.</description>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <label>Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeCardCreatorController.cls
// Controller used to create time cards for students working on the current day
public class TimeCardCreatorController {

    public Boolean isFriday { get; set; }
    public Boolean hasFoundStudents { get; set; }
    public List<SelectOption> dayOptions { get; set; }
    public string selectedDay { get; set; }

    private List<StudentViewModel> students;
    private List<StudentViewModel> studentsWithCards;
    private List<Time_Card__c> timeCardsForToday;
    private List<string> studentIds;
    private string statusMessage;
    private string createMessage;
    private DateTime today;
    private String dayOfWeek;
        
    public TimeCardCreatorController()
    {
        today = DateTime.Now();
        dayOfWeek = today.format('EEEE');
        if(dayOfWeek == 'Friday')
        {     
            isFriday = true;
        } 
        else 
        {   
            isFriday = false;
        }
        dayOptions = new List<SelectOption>();
        dayOptions.add(new SelectOption('Choose Day', 'Choose Day'));
        dayOptions.add(new SelectOption('Monday', 'Monday'));
        dayOptions.add(new SelectOption('Tuesday', 'Tuesday'));
        dayOptions.add(new SelectOption('Wednesday', 'Wednesday'));
        dayOptions.add(new SelectOption('Thursday', 'Thursday'));
        students = new List<StudentViewModel>();
        studentsWithCards = new List<StudentViewModel>();
        studentIds = new List<string>();
        createMessage = '';
        
        timeCardsForToday = [SELECT Id,
            Student__r.Id,
            Date__c
            FROM Time_Card__c
            WHERE Date__c = TODAY];
        for (Time_Card__c timeCard : timeCardsForToday)
        {
            studentIds.Add(timeCard.Student__r.Id);
        }
    }
    
    // Find the students whose work day is set to the current day of the week
    public PageReference findStudents() {        
        
        students = new List<StudentViewModel>();
        studentsWithCards = new List<StudentViewModel>();
    
        List<Student__c> possibleStudents = [SELECT Id,
        Name,
        Student_Email__c,
        Sponsor__c,
        Sponsor__r.Id,
        Sponsor__r.Name,
        Sponsor_Contact__c,
        Sponsor_Contact__r.Id,
        Sponsor_Contact__r.Name,
        Split_Time_Sponsor__c,
        Split_Time_Sponsor__r.Id,
        Split_Time_Sponsor__r.Name,
        Split_Time_Sponsor_Contact__c,
        Split_Time_Sponsor_Contact__r.Id,
        Split_Time_Sponsor_Contact__r.Name,
        Split_time__c,
        Withdrawn__c,
        Graduate__c,
        IsWorking__c
        FROM Student__c
        WHERE Work_Day__c =: dayOfWeek AND Withdrawn__c =: false AND Graduate__c =: false AND Id NOT IN :studentIds];
        
        for(Student__c student : possibleStudents) {
            if(isFriday && student.Split_time__c) {
                students.add(new StudentViewModel(student, true));
            }
            else {
                students.add(new StudentViewModel(student, false));
            }
        }
        
        statusMessage = 'Students available today: ' + students.size();
        hasFoundStudents = TRUE;
        
        List<Student__c> allStudentsWithCards = [SELECT Id,
            Name,
            Student_Email__c,
            Sponsor__c,
            Sponsor__r.Id,
            Sponsor__r.Name,
            Sponsor_Contact__c,
            Sponsor_Contact__r.Id,
            Sponsor_Contact__r.Name,
            Split_Time_Sponsor__c,
            Split_Time_Sponsor__r.Id,
            Split_Time_Sponsor__r.Name,
            Split_Time_Sponsor_Contact__c,
            Split_Time_Sponsor_Contact__r.Id,
            Split_Time_Sponsor_Contact__r.Name,
            Split_time__c,
            IsWorking__c
            FROM Student__c
            WHERE Work_Day__c =: dayofWeek AND Id IN :studentIds ];
        
        for(Student__c student : allStudentsWithCards ) {
            if(isFriday && student.Split_time__c) {
                studentsWithCards.add(new StudentViewModel(student, true));
            }
            else {
                studentsWithCards.add(new StudentViewModel(student, false));
            }
        }
        
        return null;
    }

    // Set the selected day based on the day picker and get timecards/students for that day
    public PageReference setSelectedDay() {
    
        List<Student__c> possibleStudents;
        if(selectedDay != 'Choose Day')
        {
            students = new List<StudentViewModel>();
            studentsWithCards = new List<StudentViewModel>();
        
            possibleStudents= [SELECT Id,
                Name,
                Student_Email__c,
                Sponsor__c,
                Sponsor__r.Id,
                Sponsor__r.Name,
                Sponsor_Contact__c,
                Sponsor_Contact__r.Id,
                Sponsor_Contact__r.Name,
                Split_Time_Sponsor__c,
                Split_Time_Sponsor__r.Id,
                Split_Time_Sponsor__r.Name,
                Split_Time_Sponsor_Contact__c,
                Split_Time_Sponsor_Contact__r.Id,
                Split_Time_Sponsor_Contact__r.Name,
                Split_time__c,
                Withdrawn__c,
                Graduate__c,
                IsWorking__c
                FROM Student__c
                WHERE Work_Day__c =: selectedDay AND Withdrawn__c =: false AND Graduate__c =: false AND Id NOT IN :studentIds];
            
            // Show each student as working so users don't have to click a bunch of checkboxes
            for(Student__c s : possibleStudents) {
                s.IsWorking__c = false;
                if(isFriday && s.Split_time__c) {
                    students.add(new StudentViewModel(s, true));
                }
                else {
                    students.add(new StudentViewModel(s, false));
                }
            }
        
            statusMessage = 'Students available today: ' + students.size();
            hasFoundStudents = TRUE;
            
            List<Student__c> allStudentsWithCards = [SELECT Id,
                Name,
                Student_Email__c,
                Sponsor__c,
                Sponsor__r.Id,
                Sponsor__r.Name,
                Sponsor_Contact__c,
                Sponsor_Contact__r.Id,
                Sponsor_Contact__r.Name,
                Split_Time_Sponsor__c,
                Split_Time_Sponsor__r.Id,
                Split_Time_Sponsor__r.Name,
                Split_Time_Sponsor_Contact__c,
                Split_Time_Sponsor_Contact__r.Id,
                Split_Time_Sponsor_Contact__r.Name,
                Split_time__c,
                IsWorking__c
                FROM Student__c
                WHERE Work_Day__c =: selectedDay AND Id IN :studentIds ];
                
            for(Student__c student : allStudentsWithCards ) {
                if(isFriday && student.Split_time__c) {
                    studentsWithCards.add(new StudentViewModel(student, true));
                }
                else {
                    studentsWithCards.add(new StudentViewModel(student, false));
                }
            }
        }
        else
        {
            hasFoundStudents = FALSE;
            students = new List<StudentViewModel>();
            studentsWithCards = new List<StudentViewModel>();
        }
        
        return null;
    }
    
     // Create new time cards for the selected students
    public PageReference createTimeCards()
    {
        try
        {
            List<Time_Card__c> newCards = new List<Time_Card__c>();
            
            for(StudentViewModel student : students)
            {
                if(student.IsWorking)
                {
                    
                    Time_Card__c newTimeCard = new Time_Card__c
                    (
                        Student__c = student.StudentId,
                        Student_Email__c = student.Email,
                        Date__c = date.Today(),
                        Supervisor__c = student.ContactId
                    );
                    newCards.add(newTimeCard);
                }
            }
            insert newCards;
            createMessage = 'Time cards created successfully';
        }
        catch(Exception e)
        {
            createMessage = e.getMessage();
        }
        return null;
    }
    
    public string getStatusMessage()
    {
        return statusMessage;
    }
    public String getCreateMessage() 
    {
        return createMessage;
    }
    public List<StudentViewModel> getStudents()
    {
        return students;
    }
    public List<StudentViewModel> getStudentsWithCards()
    {
        return studentsWithCards ;
    }
    public string getDayOfWeek()
    {
        return dayOfWeek;
    }
    public List<SelectOption> getDayOptions() 
    {
        return dayOptions;
    }
    
    //Student View Model used to abstract away logic around split time students
    public class StudentViewModel {
        public Student__c StudentObject;
        public Id StudentId;
        public string Name { get; set;}
        public string Email;
        public boolean IsWorking { get; set;}
        public boolean IsSplitTime;
        
        public Id SponsorId;
        public string SponsorName { get; set;}
        public Id ContactId;
        public string ContactName { get; set;}
       
      // public boolean getIsWorking() { return IsWorking; }
        
        public StudentViewModel() { }
        public StudentViewModel(Student__c student, boolean isSplitTime) {
            this.studentObject = student;
            this.StudentId = student.Id;
            this.Name = student.Name;
            this.Email = student.Student_Email__c;
            this.IsWorking = student.IsWorking__c;
            this.IsSplitTime = isSplitTime;
            if(isSplitTime) {
                this.SponsorId = student.Split_Time_Sponsor__r.Id;
                this.SponsorName = student.Split_Time_Sponsor__r.Name;
                this.ContactId = student.Split_Time_Sponsor_Contact__r.Id;
                this.ContactName = student.Split_Time_Sponsor_Contact__r.Name;
            }
            else {
                this.SponsorId = student.Sponsor__r.Id;
                this.SponsorName = student.Sponsor__r.Name;
                this.ContactId = student.Sponsor_Contact__r.Id;
                this.ContactName = student.Sponsor_Contact__r.Name;
            }
        }
    }

}