src/objects/Student__c.object
<CustomObject>
    <description>This object stores information about CRJ students.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>The first name of the student.</description>
        <label>First Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <description>Student&apos;s email address</description>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <description>Time Card used to track a student&apos;s daily hours and performance at their sponsor.</description>
    <fields>
        <fullName>Contact_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the sponsor has submitted this time card.</description>
        <label>Contact Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_URL__c</fullName>
        <formula>&apos;http://cristorey.force.com/apex/SupervisorTimeCardEntry?c=&apos;+URL_Encoded_Hash__c</formula>
        <label>Contact URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hash__c</fullName>
        <label>Hash</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <label>Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeCardSponsorControllerTest.cls
@isTest 
private class TimeCardSponsorControllerTest{
    static testMethod void validateSponsorTimeCard() {        
        // Arrange
        Student__c s = new Student__c(First_Name__c = 'First', Last_Name__c = 'Last', Student_Email__c = 'student@test.com');
        insert s;
        Contact c = new Contact(LastName = 'Last');
        insert c;
        Time_Card__c t = new Time_Card__c (Student__c = s.id, Supervisor__c = c.id);
        insert t;
        Time_Card__c expected = [SELECT Name,
                Date__c,
                Hash__c,
                Contact_URL__c,
                Supervisor__r.Name,
                Contact_Submitted__c
            FROM Time_Card__c WHERE Id =:t.Id];
        
        PageReference pageRef = Page.SupervisorTimeCardEntry;
        Test.setCurrentPage(pageRef);
        ApexPages.CurrentPage().getParameters().put('c', expected.Hash__c);
        
        // Act
        TimeCardSponsorController controller = new TimeCardSponsorController();
        Time_Card__c actual =  controller.getTimeCard();
        string actualSupervisorName = controller.getSupervisorName();
        Boolean actualCanEdit = controller.GetCanEdit();
        string actualStatusMessage = controller.getStatusMessage();
        
        // Assert
        System.assertEquals(expected.Hash__c, actual.Hash__c);
        System.assertEquals(expected.Supervisor__r.Name, actualSupervisorName);
        System.assertEquals(!expected.Contact_Submitted__c, actualCanEdit);
        
        controller.save();
        PageReference actualRef = controller.reload();
        System.assertEquals(expected.Contact_URL__c, actualRef.getUrl());
    }   
}