src/objects/Student__c.object
<CustomObject>
    <description>This object stores information about CRJ students.</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <description>Time Card used to track a student&apos;s daily hours and performance at their sponsor.</description>
    <fields>
        <fullName>Contact_Me__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Please check if you would like a member of CWSP to contact you.</description>
        <label>Contact Me</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Submitted_Date__c</fullName>
        <description>The Date/Time that the student&apos;s contact submitted their time card</description>
        <label>Contact Submitted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the sponsor has submitted this time card.</description>
        <label>Contact Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_URL__c</fullName>
        <formula>&apos;http://cristorey.force.com/apex/SupervisorTimeCardEntry?c=&apos;+URL_Encoded_Hash__c</formula>
        <label>Contact URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hash__c</fullName>
        <label>Hash</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <formula>Total_Hours__c -  Lunch_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hours Worked</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lunch_In__c</fullName>
        <label>Lunch In</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lunch_Out__c</fullName>
        <label>Lunch Out</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lunch_Time__c</fullName>
        <formula>IF ( ((Lunch_In__c - Lunch_Out__c )) &gt; 0,
24 * ( ((Lunch_In__c - Lunch_Out__c)) )
, 0)</formula>
        <label>Lunch Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Student_Description__c</fullName>
        <description>Please write a brief description about your activities for the day.</description>
        <label>Student Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Supervisor_Comments__c</fullName>
        <description>Please comment the student’s work performance. (Please contact the CWSP office if necessary.)

Important Numbers: Mr. Dan Walsh 713-725-4093 Mrs. Brandice Pierre 713-724-7903</description>
        <label>Supervisor Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <label>Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <formula>IF ( ((End_Time__c - Start_Time__c )) &gt; 0,
24 * ( ((End_Time__c - Start_Time__c )) )
, 0)</formula>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeCardSponsorController.cls
// Controller used to get and update Time Card information provided by the sponsor.
public class TimeCardSponsorController
{

    public String getSupervisorName() {
        return supervisorName;
    }

    private final Time_Card__c timeCard;
    private string statusMessage;
    private string supervisorName;
    
    public TimeCardSponsorController()
    {
        timeCard = [SELECT 
        Id,
        Contact_Me__c, 
        Date__c,
        Contact_Submitted__c,
        Contact_URL__c,
        End_Time__c, 
        Hash__c,
        Hours_Worked__c, 
        Lunch_In__c, 
        Lunch_Out__c, 
        Lunch_Time__c, 
        Name,
        Start_Time__c, 
        Student__c,
        Supervisor__r.Name,
        Student__r.Name,
        Student_Description__c,
        Supervisor_Comments__c,
        Total_Hours__c,
        Contact_Submitted_Date__c
        FROM Time_Card__c
        WHERE Hash__c =:ApexPages.currentPage().getParameters().get('c')];
        
        supervisorName = timeCard.Supervisor__r.Name;
        
        if(timeCard.Contact_Submitted__c)
        {
            statusMessage = 'Thank you for submitting your time card for ' + timeCard.Student__r.Name + '!';
        }
        else
        {
            DateTime dT = timeCard.Date__c;
            statusMessage = 'Please confirm and comment on the ' + dT.format('MMMMM dd, yyyy', 'Etc./GMT') + ' time card for ' + timeCard.Student__r.Name + '.';
        }
    }
    
    public boolean getCanEdit()
    {
        return !timeCard.Contact_Submitted__c;
    }
    
    public string getStatusMessage()
    {
        return statusMessage;
    }
    
    public Time_Card__c getTimeCard()
    {
        return timeCard;
    }
    
    public void save()
    {
        boolean success = false;
        try{
            update timeCard;
            success = true;
        }catch(Exception e){
            ApexPages.addMessages(e);
            success = false;
        }
        
        if(success) {
            timeCard.Contact_Submitted_Date__c = Datetime.now();
            timeCard.Contact_Submitted__c = true;
            update timeCard;
            reload();
        }
    }
    
    public PageReference reload()
    {        
        statusMessage = 'Thank you for submitting your time card for ' + timeCard.Student__r.Name + '!';
        
        if(timeCard.Contact_URL__c != null){
            return new PageReference(timeCard.Contact_URL__c);
            } else {
            return null;
            }
    }     
}