src/objects/Student__c.object
<CustomObject>
    <description>This object stores information about CRJ students.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>The first name of the student.</description>
        <label>First Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <description>Student&apos;s email address</description>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <description>Time Card used to track a student&apos;s daily hours and performance at their sponsor.</description>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hash__c</fullName>
        <label>Hash</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <label>Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateHashTestClass.cls
@isTest 
private class GenerateHashTestClass{
    static testMethod void validateGenerateHash() {
        // Arrange
        Student__c s = new Student__c(First_Name__c = 'First', Last_Name__c = 'Last', Student_Email__c = 'student@test.com');
        insert s;
        Contact c = new Contact(LastName = 'Last');
        insert c;
        Time_Card__c t = new Time_Card__c (Student__c = s.id, Supervisor__c = c.id);
        
        // Act
        insert t;
        
        // Retrieve the new time card
        t = [SELECT Name, Date__c, Hash__c, Student__r.Name FROM Time_Card__c WHERE Id =:t.Id];
        
        // Determine what the expected hash should be based on the time card's name
        Blob hash = Crypto.generateDigest('MD5', Blob.valueOf(String.valueOf(t.Date__c)+String.valueOf(t.Student__r.Name)));
        String expected = EncodingUtil.base64Encode(hash);
        
        // Assert
        System.assertEquals(expected, t.Hash__c);
    }
}