src/objects/Student__c.object
<CustomObject>
    <description>This object stores information about CRJ students.</description>
    <fields>
        <fullName>Split_Time_Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Split Time Sponsor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students (Split Time Sponsor)</relationshipLabel>
        <relationshipName>Students1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Cell_Phone__c</fullName>
        <label>Student Cell Phone</label>
        <type>Phone</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <description>Time Card used to track a student&apos;s daily hours and performance at their sponsor.</description>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hash__c</fullName>
        <label>Hash</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <formula>Total_Hours__c -  Lunch_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hours Worked</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lunch_In__c</fullName>
        <label>Lunch In</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lunch_Out__c</fullName>
        <label>Lunch Out</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lunch_Time__c</fullName>
        <formula>IF ( ((Lunch_In__c - Lunch_Out__c )) &gt; 0,
24 * ( ((Lunch_In__c - Lunch_Out__c)) )
, 0)</formula>
        <label>Lunch Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Student_Description__c</fullName>
        <description>Please write a brief description about your activities for the day.</description>
        <label>Student Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Student_Submitted_Date__c</fullName>
        <description>The Date/Time that the student submitted their time card</description>
        <label>Student Submitted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Student_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the student has submitted this time card.</description>
        <label>Student Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student_URL__c</fullName>
        <formula>&apos;http://cristorey.force.com/apex/StudentTimeCardEntry?s=&apos; + URL_Encoded_Hash__c</formula>
        <label>Student URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <label>Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <formula>IF ( ((End_Time__c - Start_Time__c )) &gt; 0,
24 * ( ((End_Time__c - Start_Time__c )) )
, 0)</formula>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeCardStudentController.cls
// Controller used to get and update Time Card information provided by the student.
public class TimeCardStudentController
{
    private final Time_Card__c timeCard;
    private Student__c student;
    private string supervisorName;
    private string statusMessage;
    private final string queryHash;
    
    public TimeCardStudentController()
    {
        if(ApexPages.currentPage().getParameters().containsKey('s')){
            queryHash = ApexPages.currentPage().getParameters().get('s');   
        }
        
        timeCard = [SELECT Id, Date__c,
        End_Time__c, 
        Hash__c,
        Hours_Worked__c, 
        Lunch_In__c, 
        Lunch_Out__c, 
        Lunch_Time__c, 
        Name,
        Start_Time__c, 
        Student_Submitted__c,
        Student__r.Id,
        Student__r.Name,
        Student__r.Student_Cell_Phone__c,
        Student__r.Sponsor__c,
        Student__r.Sponsor__r.Name,
        Student__r.Split_Time_Sponsor__r.Name,
        Student_Description__c,
        Student_URL__c,
        Supervisor__r.Name,
        Supervisor__r.Account.Name,
        Total_Hours__c,
        Student_Submitted_Date__c
        FROM Time_Card__c
        WHERE Hash__c =:queryHash];
        
        DateTime dateDateTime = timeCard.Date__c;
        String dateString = dateDateTime.format('MMMMM dd, yyyy', 'Etc./GMT');

        if(timeCard.Student_Submitted__c)
        {
            statusMessage = 'Thank you for submitting your time card for ' + dateString + '!';
        }
        else
        {
            statusMessage = 'Please fill out your timesheet for ' + dateString + '.';
        }
    }
    
    public Time_Card__c getTimeCard()
    {
        return timeCard;
    }
    
    public string getStatusMessage()
    {
        return statusMessage;
    }
    
    public string getSupervisorName()
    {
        return supervisorName;
    }
    
    public PageReference reload()
    {        
        // Set success message
        DateTime dT = timeCard.Date__c;
        statusMessage = 'Thank you for submitting your time card for ' + dT.format('MMMMM dd, yyyy', 'Etc./GMT') + '!';
        
        if(timeCard.Student_URL__c != null) {
            return new PageReference(timeCard.Student_URL__c);
        } else {
            return null;
        }
    }
    
    public void save()
    {
        boolean success = false;
        try {
        // Attempt to update the time card
            update timeCard;
            
        // Attempt to update the student's phone number
            student = [SELECT Id,
            Student_Cell_Phone__c
            FROM Student__c 
            WHERE Student__c.Id =: timeCard.Student__r.Id];
            student.Student_Cell_Phone__c = timeCard.Student__r.Student_Cell_Phone__c;
            update student;
            
            success = true;
        } catch (Exception e) {
        // If there are errors, present them on the page
            ApexPages.addMessages(e);
            success = false;
        }        
        
        if (success) {
        // If the time card can be updated, do so and reload the page
            timeCard.Student_Submitted_Date__c = Datetime.now();
            timeCard.Student_Submitted__c = true;
            update timeCard;
            reload();
        }
    }
    
    public boolean getCanEdit()
    {
        return !timeCard.Student_Submitted__c;
    }
}