src/objects/Student__c.object
<CustomObject>
    <description>This object stores information about CRJ students.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>The first name of the student.</description>
        <label>First Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <description>Student&apos;s email address</description>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Work_Day__c</fullName>
        <description>This is the day the student works each week.</description>
        <inlineHelpText>What day of the week does the student work?</inlineHelpText>
        <label>Work Day</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimeCardCreatorControllerTest.cls
@isTest 
private class TimeCardCreatorControllerTest{
    static testMethod void validateTimeCardCreator() {
        // Arrange
        string dayOfWeek = 'Thursday';
        Student__c s = new Student__c(First_Name__c = 'First', Last_Name__c = 'Last', Student_Email__c = 'student@test.com', Work_Day__c = 'Monday');
        insert s;
        Contact c = new Contact(LastName = 'Last');
        insert c;
        
        // Act
        TimeCardCreatorController controller = new TimeCardCreatorController();
        controller.findStudents();
        controller.createTimeCards();
        controller.getCreateMessage();
        controller.getStatusMessage();
        controller.setSelectedDay();
        
        // Assert
        System.assertEquals(false, controller.isFriday);
        System.assertEquals(0, controller.getStudents().size());
    }

    static testMethod void validateTimeCardCreatorOnFriday() {
        // Arrange
        Student__c s = new Student__c(First_Name__c = 'First', Last_Name__c = 'Last', Student_Email__c = 'student@test.com', Work_Day__c = 'Thursday');
        insert s;
        Contact c = new Contact(LastName = 'Last');
        insert c;
        
        // Act
        TimeCardCreatorController controller = new TimeCardCreatorController();
        controller.selectedDay = 'Thursday';
        controller.setSelectedDay();
        controller.createTimeCards();
        
        // Assert
        System.assertEquals(DateTime.Now().format('EEEE') == 'Friday', controller.isFriday);
        System.assertEquals(1, controller.getStudents().size());
    }
}